# -*- coding: utf-8 -*-
"""產生 STM32 V2 gating 的固定頻率測試向量。

每組向量皆為 100 Hz、GyroX 單軸資料：
  0–1 s  靜置
  1–5 s  固定頻率正弦波，峰值 15 deg/s
  5–7 s  靜置

輸出 CSV 供人工檢查，另輸出 int16 C header 供韌體測試模式直接載入。
BNO055 dps 模式的比例為 raw / 16 = deg/s。
"""

from __future__ import annotations

import argparse
import csv
import json
import math
from pathlib import Path


FS_HZ = 100
AMPLITUDE_DPS = 15.0
REST_BEFORE_SECONDS = 1
TONE_SECONDS = 4
REST_AFTER_SECONDS = 2
TOTAL_SECONDS = REST_BEFORE_SECONDS + TONE_SECONDS + REST_AFTER_SECONDS
SAMPLE_COUNT = FS_HZ * TOTAL_SECONDS
RAW_LSB_PER_DPS = 16
FREQUENCIES_HZ = (1, 2, 3, 4, 5, 6, 8)
EXPECTED_SHOULD_ENABLE = (0, 0, 0, 1, 1, 1, 0)


def make_vector(frequency_hz: int) -> list[int]:
    """回傳量化成 BNO055 raw int16 的 GyroX 測試資料。"""
    samples: list[int] = []
    tone_start = REST_BEFORE_SECONDS * FS_HZ
    tone_end = tone_start + TONE_SECONDS * FS_HZ

    for index in range(SAMPLE_COUNT):
        if tone_start <= index < tone_end:
            tone_time = (index - tone_start) / FS_HZ
            dps = AMPLITUDE_DPS * math.sin(
                2.0 * math.pi * frequency_hz * tone_time
            )
        else:
            dps = 0.0
        raw = int(round(dps * RAW_LSB_PER_DPS))
        if not -32768 <= raw <= 32767:
            raise ValueError("測試向量超出 int16 範圍")
        samples.append(raw)
    return samples


def write_csv(path: Path, frequency_hz: int, raw_samples: list[int]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tone_start = REST_BEFORE_SECONDS * FS_HZ
    tone_end = tone_start + TONE_SECONDS * FS_HZ
    with path.open("w", encoding="utf-8", newline="") as stream:
        writer = csv.writer(stream, lineterminator="\n")
        writer.writerow(
            [
                "sequence",
                "sample_tick_ms",
                "gyro_x_raw_lsb",
                "gyro_x_dps",
                "segment",
            ]
        )
        for index, raw in enumerate(raw_samples):
            if index < tone_start:
                segment = "rest_before"
            elif index < tone_end:
                segment = f"tone_{frequency_hz}hz"
            else:
                segment = "rest_after"
            writer.writerow(
                [index, index * 10, raw, f"{raw / RAW_LSB_PER_DPS:.4f}", segment]
            )


def _format_c_array(values: list[int], indent: str = "        ") -> str:
    lines: list[str] = []
    for start in range(0, len(values), 16):
        chunk = values[start : start + 16]
        suffix = "," if start + 16 < len(values) else ""
        lines.append(indent + ", ".join(str(value) for value in chunk) + suffix)
    return "\n".join(lines)


def write_header(path: Path, vectors: dict[int, list[int]]) -> None:
    frequency_list = ", ".join(str(value) for value in FREQUENCIES_HZ)
    enable_list = ", ".join(str(value) for value in EXPECTED_SHOULD_ENABLE)
    rows = []
    for frequency_hz in FREQUENCIES_HZ:
        rows.append("    {\n" + _format_c_array(vectors[frequency_hz]) + "\n    }")

    contents = f"""/* Auto-generated by algorithms/validation/generate_gating_frequency_vectors.py.
 * Do not edit the sample values by hand.
 * BNO055 conversion: gyro_dps = raw_lsb / 16.0.
 */
#ifndef STEADYHOPE_GATING_FREQUENCY_VECTORS_H
#define STEADYHOPE_GATING_FREQUENCY_VECTORS_H

#include <stdint.h>

#define GATING_TEST_VECTOR_COUNT {len(FREQUENCIES_HZ)}U
#define GATING_TEST_SAMPLE_COUNT {SAMPLE_COUNT}U
#define GATING_TEST_FS_HZ {FS_HZ}U
#define GATING_TEST_RAW_LSB_PER_DPS {RAW_LSB_PER_DPS}.0
#define GATING_TEST_TONE_START_SAMPLE {REST_BEFORE_SECONDS * FS_HZ}U
#define GATING_TEST_TONE_END_SAMPLE {(REST_BEFORE_SECONDS + TONE_SECONDS) * FS_HZ}U

static const uint8_t GATING_TEST_FREQUENCIES_HZ[GATING_TEST_VECTOR_COUNT] = {{
    {frequency_list}
}};

/* 0: enabled must remain 0; 1: enabled must become 1 during the tone. */
static const uint8_t GATING_TEST_EXPECTED_SHOULD_ENABLE[GATING_TEST_VECTOR_COUNT] = {{
    {enable_list}
}};

static const int16_t
GATING_TEST_GYRO_X_RAW_LSB[GATING_TEST_VECTOR_COUNT][GATING_TEST_SAMPLE_COUNT] = {{
{',\n'.join(rows)}
}};

#endif
"""
    path.write_text(contents, encoding="utf-8", newline="\n")


def write_manifest(path: Path) -> None:
    payload = {
        "schema_version": 1,
        "sample_rate_hz": FS_HZ,
        "raw_lsb_per_dps": RAW_LSB_PER_DPS,
        "amplitude_peak_dps": AMPLITUDE_DPS,
        "rest_before_seconds": REST_BEFORE_SECONDS,
        "tone_seconds": TONE_SECONDS,
        "rest_after_seconds": REST_AFTER_SECONDS,
        "sample_count_per_vector": SAMPLE_COUNT,
        "vectors": [
            {
                "frequency_hz": frequency,
                "csv": f"gating_{frequency:02d}hz.csv",
                "expected_should_enable": bool(expected),
            }
            for frequency, expected in zip(
                FREQUENCIES_HZ, EXPECTED_SHOULD_ENABLE, strict=True
            )
        ],
        "scope": "Synthetic algorithm-injection test only; not human tremor data.",
    }
    path.write_text(
        json.dumps(payload, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
        newline="\n",
    )


def generate(output_dir: Path) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    vectors = {frequency: make_vector(frequency) for frequency in FREQUENCIES_HZ}
    for frequency, samples in vectors.items():
        write_csv(output_dir / f"gating_{frequency:02d}hz.csv", frequency, samples)
    write_header(output_dir / "gating_frequency_vectors.h", vectors)
    write_manifest(output_dir / "manifest.json")


def main() -> None:
    default_output = (
        Path(__file__).resolve().parents[1]
        / "handoff"
        / "test_vectors"
        / "gating_frequency"
    )
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-dir", type=Path, default=default_output)
    args = parser.parse_args()
    generate(args.output_dir)
    print(
        f"generated {len(FREQUENCIES_HZ)} vectors x {SAMPLE_COUNT} samples "
        f"in {args.output_dir}"
    )


if __name__ == "__main__":
    main()
