# -*- coding: utf-8 -*-
"""產生7 Hz／10、15、20 deg/s的STM32 V2 gating邊界測試包。"""

from __future__ import annotations

import argparse
import csv
import json
import math
from pathlib import Path

from tremor_gate_reference import TremorGateReference


FS_HZ = 100
FREQUENCY_HZ = 7.0
AMPLITUDES_DPS = (10.0, 15.0, 20.0)
REST_BEFORE_SECONDS = 1
TONE_SECONDS = 4
REST_AFTER_SECONDS = 2
TOTAL_SECONDS = REST_BEFORE_SECONDS + TONE_SECONDS + REST_AFTER_SECONDS
SAMPLE_COUNT = FS_HZ * TOTAL_SECONDS
RAW_LSB_PER_DPS = 16


def case_id(amplitude_dps: float) -> str:
    return f"7hz_{int(amplitude_dps):02d}dps"


def make_vector(amplitude_dps: float) -> list[int]:
    """回傳量化成BNO055 raw int16的單軸7 Hz測試資料。"""
    samples: list[int] = []
    tone_start = REST_BEFORE_SECONDS * FS_HZ
    tone_end = tone_start + TONE_SECONDS * FS_HZ
    for index in range(SAMPLE_COUNT):
        if tone_start <= index < tone_end:
            tone_time = (index - tone_start) / FS_HZ
            dps = amplitude_dps * math.sin(
                2.0 * math.pi * FREQUENCY_HZ * tone_time
            )
        else:
            dps = 0.0
        raw = int(round(dps * RAW_LSB_PER_DPS))
        if not -32768 <= raw <= 32767:
            raise ValueError("測試向量超出int16範圍")
        samples.append(raw)
    return samples


def run_reference(
    vectors: dict[float, list[int]],
) -> dict[float, list[dict[str, float | int | str]]]:
    traces: dict[float, list[dict[str, float | int | str]]] = {}
    for amplitude_dps in AMPLITUDES_DPS:
        gate = TremorGateReference()
        rows: list[dict[str, float | int | str]] = []
        for sample_index, raw in enumerate(vectors[amplitude_dps]):
            gyro_x_dps = raw / RAW_LSB_PER_DPS
            gate.update(gyro_x_dps)
            row: dict[str, float | int | str] = {
                "test_case_id": case_id(amplitude_dps),
                "frequency_hz": FREQUENCY_HZ,
                "amplitude_peak_dps": amplitude_dps,
                "sample_index": sample_index,
                "sample_tick_ms": sample_index * 10,
                "gyro_x_raw_lsb": raw,
                "gyro_x_dps": gyro_x_dps,
            }
            row.update(gate.snapshot())
            rows.append(row)
        traces[amplitude_dps] = rows
    return traces


def write_vector_csv(path: Path, amplitude_dps: float, samples: list[int]) -> None:
    tone_start = REST_BEFORE_SECONDS * FS_HZ
    tone_end = tone_start + TONE_SECONDS * FS_HZ
    with path.open("w", encoding="utf-8", newline="") as stream:
        writer = csv.writer(stream, lineterminator="\n")
        writer.writerow([
            "test_case_id", "sequence", "sample_tick_ms",
            "gyro_x_raw_lsb", "gyro_x_dps", "segment",
        ])
        for index, raw in enumerate(samples):
            if index < tone_start:
                segment = "rest_before"
            elif index < tone_end:
                segment = "tone_7hz"
            else:
                segment = "rest_after"
            writer.writerow([
                case_id(amplitude_dps), index, index * 10, raw,
                f"{raw / RAW_LSB_PER_DPS:.4f}", segment,
            ])


def _format_c_array(values: list[int], indent: str = "        ") -> str:
    lines: list[str] = []
    for start in range(0, len(values), 16):
        chunk = values[start:start + 16]
        suffix = "," if start + 16 < len(values) else ""
        lines.append(indent + ", ".join(str(value) for value in chunk) + suffix)
    return "\n".join(lines)


def write_header(
    path: Path,
    vectors: dict[float, list[int]],
    traces: dict[float, list[dict[str, float | int | str]]],
) -> None:
    amplitudes = ", ".join(f"{value:.1f}F" for value in AMPLITUDES_DPS)
    raw_rows: list[str] = []
    expected_rows: list[str] = []
    reference_did_enable: list[str] = []
    for amplitude_dps in AMPLITUDES_DPS:
        raw_rows.append(
            "    {\n" + _format_c_array(vectors[amplitude_dps]) + "\n    }"
        )
        expected = [int(row["enabled"]) for row in traces[amplitude_dps]]
        expected_rows.append(
            "    {\n" + _format_c_array(expected) + "\n    }"
        )
        reference_did_enable.append("1" if any(expected) else "0")

    contents = f"""/* Auto-generated by generate_gating_7hz_boundary_vectors.py.
 * Synthetic algorithm-injection data only; not human tremor data.
 */
#ifndef STEADYHOPE_GATING_7HZ_BOUNDARY_VECTORS_H
#define STEADYHOPE_GATING_7HZ_BOUNDARY_VECTORS_H

#include <stdint.h>

#define GATING_7HZ_VECTOR_COUNT {len(AMPLITUDES_DPS)}U
#define GATING_7HZ_SAMPLE_COUNT {SAMPLE_COUNT}U
#define GATING_7HZ_FS_HZ {FS_HZ}U
#define GATING_7HZ_FREQUENCY_HZ 7.0F
#define GATING_7HZ_RAW_LSB_PER_DPS {RAW_LSB_PER_DPS}.0
#define GATING_7HZ_TONE_START_SAMPLE {REST_BEFORE_SECONDS * FS_HZ}U
#define GATING_7HZ_TONE_END_SAMPLE {(REST_BEFORE_SECONDS + TONE_SECONDS) * FS_HZ}U

static const float GATING_7HZ_AMPLITUDES_DPS[GATING_7HZ_VECTOR_COUNT] = {{
    {amplitudes}
}};

/* Design target: 7 Hz is outside the 4-6 Hz pass band, so all should stay off. */
static const uint8_t
GATING_7HZ_DESIGN_SHOULD_ENABLE[GATING_7HZ_VECTOR_COUNT] = {{0, 0, 0}};

/* Current PC reference: 20 deg/s is a known boundary false activation. */
static const uint8_t
GATING_7HZ_REFERENCE_DID_ENABLE[GATING_7HZ_VECTOR_COUNT] = {{
    {', '.join(reference_did_enable)}
}};

static const int16_t
GATING_7HZ_GYRO_X_RAW_LSB[GATING_7HZ_VECTOR_COUNT][GATING_7HZ_SAMPLE_COUNT] = {{
{',\n'.join(raw_rows)}
}};

static const uint8_t
GATING_7HZ_EXPECTED_ENABLED[GATING_7HZ_VECTOR_COUNT][GATING_7HZ_SAMPLE_COUNT] = {{
{',\n'.join(expected_rows)}
}};

#endif
"""
    path.write_text(contents, encoding="utf-8", newline="\n")


def write_expected_trace(
    path: Path,
    traces: dict[float, list[dict[str, float | int | str]]],
) -> None:
    fieldnames = [
        "test_case_id", "frequency_hz", "amplitude_peak_dps",
        "sample_index", "sample_tick_ms", "gyro_x_raw_lsb", "gyro_x_dps",
        "tremor_envelope", "voluntary_envelope", "tremor_ratio",
        "on_count", "off_count", "enabled",
    ]
    with path.open("w", encoding="utf-8", newline="") as stream:
        writer = csv.DictWriter(stream, fieldnames=fieldnames, lineterminator="\n")
        writer.writeheader()
        for amplitude_dps in AMPLITUDES_DPS:
            writer.writerows(traces[amplitude_dps])


def summarize(
    traces: dict[float, list[dict[str, float | int | str]]],
) -> list[dict[str, float | int | str]]:
    tone_start = REST_BEFORE_SECONDS * FS_HZ
    tone_end = tone_start + TONE_SECONDS * FS_HZ
    summaries: list[dict[str, float | int | str]] = []
    for amplitude_dps in AMPLITUDES_DPS:
        rows = traces[amplitude_dps]
        first = next(
            (int(row["sample_index"]) for row in rows if int(row["enabled"])),
            None,
        )
        enabled_count = sum(
            int(rows[index]["enabled"]) for index in range(tone_start, tone_end)
        )
        summaries.append({
            "test_case_id": case_id(amplitude_dps),
            "frequency_hz": FREQUENCY_HZ,
            "amplitude_peak_dps": amplitude_dps,
            "design_should_enable": 0,
            "reference_did_enable": int(first is not None),
            "delay_from_tone_start_ms": (
                "never" if first is None else (first - tone_start) * 10
            ),
            "enabled_samples_during_400_sample_tone": enabled_count,
            "enabled_fraction_during_tone": enabled_count / 400.0,
            "final_enabled": int(rows[-1]["enabled"]),
        })
    return summaries


def write_expected_results(path: Path, rows: list[dict[str, object]]) -> None:
    with path.open("w", encoding="utf-8", newline="") as stream:
        writer = csv.DictWriter(
            stream, fieldnames=list(rows[0]), lineterminator="\n"
        )
        writer.writeheader()
        writer.writerows(rows)


def write_manifest(path: Path, summaries: list[dict[str, object]]) -> None:
    payload = {
        "schema_version": 1,
        "sample_rate_hz": FS_HZ,
        "frequency_hz": FREQUENCY_HZ,
        "amplitudes_peak_dps": list(AMPLITUDES_DPS),
        "raw_lsb_per_dps": RAW_LSB_PER_DPS,
        "rest_before_seconds": REST_BEFORE_SECONDS,
        "tone_seconds": TONE_SECONDS,
        "rest_after_seconds": REST_AFTER_SECONDS,
        "sample_count_per_vector": SAMPLE_COUNT,
        "scope": "Synthetic algorithm-injection test only; not human tremor data.",
        "cases": summaries,
    }
    path.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
        newline="\n",
    )


def generate(output_dir: Path) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    vectors = {
        amplitude_dps: make_vector(amplitude_dps)
        for amplitude_dps in AMPLITUDES_DPS
    }
    traces = run_reference(vectors)
    for amplitude_dps in AMPLITUDES_DPS:
        write_vector_csv(
            output_dir / f"gating_7hz_{int(amplitude_dps):02d}dps.csv",
            amplitude_dps,
            vectors[amplitude_dps],
        )
    summaries = summarize(traces)
    write_header(output_dir / "gating_7hz_boundary_vectors.h", vectors, traces)
    write_expected_trace(output_dir / "expected_trace.csv", traces)
    write_expected_results(output_dir / "expected_results.csv", summaries)
    write_manifest(output_dir / "manifest.json", summaries)


def main() -> None:
    default_output = (
        Path(__file__).resolve().parents[1]
        / "handoff" / "test_vectors" / "gating_7hz_boundary"
    )
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-dir", type=Path, default=default_output)
    args = parser.parse_args()
    generate(args.output_dir)
    print(
        f"generated {len(AMPLITUDES_DPS)} vectors x {SAMPLE_COUNT} samples "
        f"in {args.output_dir}"
    )


if __name__ == "__main__":
    main()
